language: java
jobs:
  include:
    - stage: compile
    - stage: test
      script: skip
    - stage: deploy
stages:
  - compile
  - test
  - name: deploy
    if: branch = master
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: kline.379@osu.edu
  password:
    secure: Rn+XoiVBR1mSsM8S2NwTWI5u9GM1zKKWKmaoPobirsfQs8hH4L6phboXvU6bt1R/Nu97meV8czF4IQ0Lc6n2FIzH8HMJvcJsXm7ofAukB2ut6eXFjBJweCl5GCNqZBbsFF6dNWZX92BFjy6N5odX3K/6XL/GmQhb032iqqCa2r+m7gsWfigLnWtOg68bYj0aGkM3FNvVojtwf5lReo+FgimpTOCk0EWjXc/BYWGMUsz6vek7iLSeFn0QbIcp4FSHurRmRqVEvKGa+g3fpuGqPkadSWfX7IOIh5LgJILS0L49jldIbJ9lzZlnD+HapYzTpl5LdKpqTpIovqFlM+sAKvUzzX3GlHHLMVy7oQGOCDnP39hOtgcebYcoGA0I2e7KZJvLV+rcZnXZWl0GkOqTYEgXxF/4d7m6P0/A1YGjnz5ZK/ulJ2Wj7kzig9sKCrPqVqYyU401gDhzQy6NbL0LTVt+t8wQGAsav3J+1btHpUbjB8hau40wyntL/FI6j8giyKz9QMp/4S5am4uj9zealsDoFQVesi6ptHaHLTb7NQWqxDl8W+0mBPKDZ2KRfHakEebjilvsP8SXrwAo9jDN4hbUlvuvvl5x8lS7KSP5KS2Lh9OEXgUSgnnu3LU0yiPMjl8j/5hFKglvBgwzjqmGKNDr5aRFGiaMXoSOG8EjL0A=
  organization: kline.379
  space: cse5914
  on:
    repo: kline379/Journey
